Vche-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    resource :heartbeat, only: :show
  end

  resource :home, controller: :home, only: :show

  namespace :my do
    resources :offline_schedules

    resources :events, only: [:index]
    resources :event_follow_requests, only: :index do
      member do
        post :accept
        post :decline
      end
    end

    resource :user do
      get :delete_form
      post :delete
    end

    resource :settings, only: [:show]
    resource :password, only: [:edit, :update]
  end

  resources :users, except: [:destroy] do
    member do
      get :info
      get :events
    end
    resources :accounts, controller: 'users/accounts' do
      member do
        get :info
      end
    end
    resources :event_memories, controller: 'users/event_memories'
  end

  resources :events do
    get :select, on: :new
    member do
      get :info
      post :follow
      post :unfollow
      post :add_user
      post :change_user
      post :remove_user
      get :appeal
    end
    resources :event_schedules
    resources :event_histories, controller: 'events/event_histories' do
      resources :event_attendances, controller: 'events/event_histories/event_attendances', only: :index
      member do
        get :info
        post :attend
        post :unattend
        post :add_user
        post :change_user
        post :remove_user
        get :appeal
      end
      resource :resolution, controller: 'events/event_histories/resolutions', only: [:edit, :update]
      resource :reschedule, controller: 'events/event_histories/reschedules', only: [:new, :create]
    end
    resources :event_follows, controller: 'events/event_follows', only: :index
    resources :event_follow_requests, controller: 'events/event_follow_requests', only: :index do
      member do
        post :withdraw
      end
    end
    resources :event_appeals, controller: 'events/event_appeals', only: [:edit, :update]

    resource :owner, controller: 'events/owners', only: [:edit, :update] do
      get :introduction
    end
    resource :visibility, controller: 'events/visibilities', only: [:show, :edit, :update]
    resource :settings, controller: 'events/settings', only: [:show]
  end

  resources :hashtags, only: [:index, :show]

  get 'login' => 'sessions#new', :as => :login
  post 'login' => "sessions#create"
  post 'logout' => 'sessions#destroy', :as => :logout
  post '/sessions/purge' => 'sessions#purge', :as => :purge_sessions

  get 'oauth/:provider/oauth', to: 'oauths#oauth', :as => :auth_at_provider
  get 'oauth/:provider/callback', to: 'oauths#callback'

  get 'tos' => 'agreements#tos', :as => :tos
  get 'privacy_policy' => 'agreements#privacy_policy', :as => :privacy_policy

  resources :agreements, only: [] do
    collection do
      get :confirm
      post :agree
    end
  end

  resource :recovery, only: [:new, :create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :done
    end
  end

  root :to => 'calendar#index'

  direct :support_email do
    Rails.application.config.x.vche.support_email
  end

  direct :support_github do
    Rails.application.config.x.vche.support_github
  end

  direct :support_twitter do
    Rails.application.config.x.vche.support_twitter
  end

  direct :support_discord do
    Rails.application.config.x.vche.support_discord
  end

  ActiveAdmin.routes(self)
end

Vche-rails/app/models/operations/event_history/request_update_user_role.rb
class Operations::EventHistory::RequestUpdateUserRole
  include Operations::Operation

  class Outsider < StandardError; end

  def initialize(event_history:, creator:, user:, approver:, role:)
    @event_history = event_history
    @creator = creator
    @user = user
    @approver = approver
    @role = role&.to_sym
  end

  def validate
    raise ArgumentError if role == :irrelevant
    raise Outsider unless EventAttendance.backstage_role?(role) || EventAttendance.backstage_role?(current_role)
  end

  def perform
    if role
      event_follow_requests.find_or_initialize_by({}).tap do |efr|
        efr.assign_attributes(approver: approver, role: role, message: '', created_user: creator, updated_user: creator)
        efr.save!
      end
    else
      event_follow_requests.destroy_all
    end
  end

  private

  attr_reader :event_history, :creator, :user, :approver, :role

  def event_follow_requests
    user.event_follow_requests.where(event: event_history.event, started_at: event_history.started_at)
  end

  def current_role
    user.event_attendances.for_event_history(event_history).first&.role&.to_sym || :irrelevant
  end
end

Vche-rails/app/controllers/event_histories_controller.rb
class EventHistoriesController < ApplicationController
  before_action :find_parent_event
  skip_before_action :require_login, only: [:index, :show]

  def index
    @event_histories = @event.event_histories.order(started_at: :desc).page(params[:page])
    @user = current_user
  end

  def show
    @event_history = find_event_history
    @user = current_user
  end

  def at
    started_at = Time.zone.parse(params[:datetime])
    @event_history = @event.recent_schedule([started_at.beginning_of_day]).detect { |h| h.started_at = started_at }
    render :show
  end

  def new
    @event_history = EventHistory.new
  end

  def edit
    @event_history = find_event_history
  end

  def create
    @event_history = @event.event_histories.build(event_history_params)
    authorize! @event_history
    @event_history.created_user = current_user
    @event_history.updated_user = current_user

    if @event_history.save
      redirect_to event_event_history_path(@event, @event_history), notice: 'EventHistory was successfully created'
    else
      render :new
    end
  end

  def update
    @event_history = find_event_history
    authorize! @event_history
    @event_history.updated_user = current_user
    if @event_history.update(event_history_params)
      redirect_to event_event_history_path(@event, @event_history), notice: 'EventHistory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event_history = find_event_history
    authorize! @event_history
    @event_history.destroy
    redirect_to events_url, notice: 'EventHistory was successfully destroyed.'
  end

  def attend
    @event_history = find_event_history
    authorize! @event_history

    role = current_user.following_event_as_backstage_member?(@event) || :participant
    if current_user.event_attendances.for_event_history(@event_history).create!(role: role)
      redirect_to event_event_history_path(@event, @event_history), notice: 'Attended.'
    else
      redirect_to event_event_history_path(@event, @event_history)
    end
  end

  def unattend
    @event_history = find_event_history
    authorize! @event_history

    if current_user.event_attendances.audience.for_event_history(@event_history).delete_all
      redirect_to event_event_history_path(@event, @event_history), notice: 'Unattended.'
    else
      redirect_to event_event_history_path(@event, @event_history)
    end
  end

  def add_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    if @user.event_attendances.for_event_history(@event_history).create!(role: params[:role])
      redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: 'Added User.'
    else
      redirect_to event_event_history_event_attendances_path(@event, @event_history)
    end
  end

  def remove_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    if @user.event_attendances.for_event_history(@event_history).delete_all
      redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: 'Removed User.'
    else
      redirect_to event_event_history_event_attendances_path(@event, @event_history)
    end
  end

  private

  def find_user
    User.friendly.find(params[:user_id])
  end

  def find_parent_event
    @event = Event.friendly.find(params[:event_id])
  end

  def find_event_history
    @event.find_or_build_history(Time.zone.parse(params[:id]))
  end

  def event_history_params
    p = params.require(:event_history).permit(:visibility, :assembled_at, :opened_at, :started_at, :ended_at, :closed_at, :resolution)
  end
end

Vche-rails/app/controllers/events/event_histories/event_attendances_controller.rb
class Events::EventHistories::EventAttendancesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def index
    authorize! @event_history
    @user = current_user
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end
end

Vche-rails/app/controllers/events/event_histories/reschedules_controller.rb
class Events::EventHistories::ReschedulesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def new
    authorize! @event_history
    @user = current_user
  end

  def create
    authorize! @event_history
    @new_event_history = Operations::EventHistory::Reschedule.new(event_history: @event_history, params: reschedule_params, user: current_user).perform!
    redirect_to [@event, @new_event_history], notice: I18n.t('notice.events/event_histories/reschedules.create.success')
  rescue Operations::EventHistory::Reschedule::Unchanged
    redirect_to [@event, @event_history], notice: I18n.t('notice.events/event_histories/reschedules.create.unchanged')
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end

  def reschedule_params
    params.require(:event_history).permit(
      :capacity,
      :assembled_at, :opened_at, :started_at, :ended_at, :closed_at
    )
  end
end

Vche-rails/app/controllers/events/event_histories/resolutions_controller.rb
class Events::EventHistories::ResolutionsController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def edit
    authorize! @event_history
  end

  def update
    authorize! @event_history
    if @event_history.update(update_params)
      redirect_to [@event, @event_history], notice: I18n.t('notice.events/event_histories/resolutions.update.success')
    else
      render :edit
    end
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end

  def update_params
    params.require(:event_history).permit(:resolution)
  end
end

Vche-rails/app/controllers/events/event_histories_controller.rb
class Events::EventHistoriesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  skip_before_action :require_login, only: [:index, :show, :appeal]

  def index
    @event_histories = @event.event_histories.order(started_at: :desc).page(params[:page])
    @user = current_user
    authorize! @event
  end

  def show
    @event_history = find_event_history
    authorize! @event_history
    @user = current_user
  end

  def info
    @event_history = find_event_history
    authorize! @event_history
    @user = current_user
  end

  def at
    started_at = Time.zone.parse(params[:datetime])
    @event_history = @event.recent_histories([started_at.beginning_of_day]).detect { |h| h.started_at = started_at }
    authorize! @event_history
    render :show
  end

  def new
    authorize! @event
    @event_history = @event.event_histories.build
  end

  def edit
    @event_history = find_event_history
    authorize! @event_history
  end

  def create
    @event_history = @event.event_histories.build(create_params)
    authorize! @event_history
    @event_history.created_user = current_user
    @event_history.updated_user = current_user

    if @event_history.save
      redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.create.success')
    else
      render :new
    end
  end

  def update
    @event_history = find_event_history
    authorize! @event_history
    @event_history.updated_user = current_user
    if @event_history.update(update_params)
      redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.update.success')
    else
      render :edit
    end
  end

  def destroy
    @event_history = find_event_history
    authorize! @event_history
    @event_history.destroy
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.destroy.success')
  end

  def attend
    @event_history = find_event_history
    authorize! @event_history

    role = current_user.following_event?(@event) || @event_history.default_audience_role
    Operations::EventHistory::UpdateUserAttendance.new(event_history: @event_history, user: current_user, role: role).perform!
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.attend.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserAttendance::UserIsAudience
    redirect_to event_event_history_path(@event, @event_history)
  end

  def unattend
    @event_history = find_event_history
    authorize! @event_history

    Operations::EventHistory::UpdateUserAttendance.new(event_history: @event_history, user: current_user, role: nil).perform!
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.unattend.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserAttendance::UserIsAudience
    redirect_to event_event_history_path(@event, @event_history)
  end

  def add_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::RequestUpdateUserRole.new(
      event_history: @event_history, creator: current_user, user: @user, approver: @user, role: params[:role]
    ).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.add_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::RequestUpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.add_user.outsider')
  end

  def change_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::UpdateUserRole.new(event_history: @event_history, user: @user, role: params[:role]).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.change_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.change_user.outsider')
  end

  def remove_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::UpdateUserRole.new(event_history: @event_history, user: @user, role: nil).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.remove_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.remove_user.outsider')
  end

  def appeal
    @event_history = find_event_history
    authorize! @event_history
    redirect_to helpers.intent_url_for(@event_history)
  end

  private

  def find_user
    User.friendly.secret_or_over.find(params[:user_id])
  end

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_event_history
    @event.find_or_build_history(Time.zone.parse(params[:id]))
  end

  def create_params
    params.require(:event_history).permit(
      :resolution, :capacity, :default_audience_role,
      :assembled_at, :opened_at, :started_at, :ended_at, :closed_at
    )
  end

  def update_params
    params.require(:event_history).permit(
      :resolution, :capacity, :default_audience_role,
      :assembled_at, :opened_at, :ended_at, :closed_at
    )
  end
end

Vche-rails/app/helpers/event_history_helper.rb
module EventHistoryHelper
  def capacity_and_attendance_text(event_history)
    if event_history.capacity > 0
      "#{event_history.event_audiences.count} / #{event_history.capacity} (#{event_history.event_backstage_members.count})"
    else
      "#{event_history.event_audiences.count} (#{event_history.event_backstage_members.count})"
    end
  end
end

Vche-rails/app/views/events/event_histories/resolutions/_form.html.slim
- event ||= nil
- event_history ||= nil

= form_with(model: event_history, url: event_event_history_resolution_path(event, event_history), method: :patch, class: '-table') do |form|
  = render_errors_header form

  = render_field form, :resolution do
    = form.select :resolution, EventHistory.resolution.emoji_options(event.official? ? :official : :unofficial)

  .actions
    - if loyalty(event_history, 'events/event_histories/resolutions').update?
      = form.submit '手動で状態を更新する'

Vche-rails/app/views/events/event_histories/resolutions/_help.html.slim
- _backstage = loyalty(@event_history, 'events/event_histories').backstage?

.panel.-roundbox
  p
    | 現在の状態：
    = inline_resolution_tag @event_history.resolution
  - case @event_history.resolution.to_sym
  - when :candidate
    p
      | 登録されたイベント予定に応じて、開催回の枠が確保されています。
    p
      = inline_resolution_tag 'announced'
      | としてイベントカレンダーに予定を追加するには、
      = _backstage ? '「イベントの開催を告知する」' : '「イベントの開催を報告する」'
      | を行ってください。
  - when :scheduled
    p
      | 登録されたイベント予定に応じて、開催回の枠が確保されています。
    p
      = inline_resolution_tag 'announced'
      | としてイベントカレンダー上で予定を確定させるには、「イベントの開催を告知する」を行ってください。
  - when :announced
    p
      | イベントの開催が告知され、イベントカレンダー上で予定が確定されています。
    p
      | イベントが完了した際には、
      = _backstage ? '「イベントを完了する」' : '「イベントの完了を報告する」'
      | を行ってください。
  - when :information
    p
      | イベントの参加者が開催情報をイベントカレンダーに共有しています。
    p
      | イベントが完了した際には、
      = _backstage ? '「イベントを完了する」' : '「イベントの完了を報告する」'
      | を行ってください。
  - when :moved
    p この開催回は時間が変更されています。
  - when :canceled
    p この開催回は開催が中止されています。
  - when :ended
    p
      | この開催回は、開催告知を行わずにイベント終了時刻を経過しています。
    p
      | もしこのイベントが開催されていた場合は、
      = _backstage ? '「イベントを完了する」' : '「イベントの完了を報告する」'
      | を行ってください。
  - when :completed
    p このイベントは無事に完了しています。おつかれさまでした。

  - if @event_history.resolution.to_sym.in? [:scheduled, :announced, :ended]
    p
      | また、
      = inline_resolution_tag 'moved'
      | でイベントの開催日時の変更を、
      = inline_resolution_tag 'canceled'
      | でイベントの中止を知らせることができます。

Vche-rails/app/views/events/event_histories/resolutions/_inline_form.html.slim
- event ||= nil
- event_history ||= nil
- resolution ||= nil
- submit_label ||= nil

- if loyalty(event_history, 'events/event_histories/resolutions').update?
  = form_with(model: event_history, url: event_event_history_resolution_path(event, event_history), method: :patch, class: '-inline') do |form|
    = form.hidden_field :resolution, value: resolution
    = form.submit submit_label

Vche-rails/app/views/events/event_histories/resolutions/_quick_inline_forms.slim
- event ||= nil
- event_history ||= nil

- _backstage = loyalty(event_history, 'events/event_histories').backstage?

- if _backstage
  - if event_history.resolution.to_sym.in?([:candidate, :scheduled])
    = render 'events/event_histories/resolutions/inline_form', event: event, event_history: event_history, resolution: :announced, submit_label: 'イベントの開催を告知する'
  - if event_history.resolution.to_sym.in?([:information, :announced, :ended]) && event_history.ended_at < Time.current
    = render 'events/event_histories/resolutions/inline_form', event: event, event_history: event_history, resolution: :completed, submit_label: 'イベントを完了する'
- else
  - if event_history.resolution.to_sym.in?([:candidate, :scheduled])
    = render 'events/event_histories/resolutions/inline_form', event: event, event_history: event_history, resolution: :information, submit_label: 'イベントの開催を報告する'
  - if event_history.resolution.to_sym.in?([:information, :announced, :ended]) && event_history.ended_at < Time.current
    = render 'events/event_histories/resolutions/inline_form', event: event, event_history: event_history, resolution: :completed, submit_label: 'イベントの完了を報告する'

Vche-rails/app/views/events/event_histories/resolutions/edit.html.slim
h1 = "#{Event.model_name.human}の#{EventHistory.human_attribute_name(:resolution)}を編集する"

= render 'events/strip', event: @event, user: @user, without_appeal: true

= render 'event_histories/strip', event: @event, event_history: @event_history, user: @user

= render 'help'

.panel.-roundbox
  = render 'quick_inline_forms', event: @event, event_history: @event_history

  = render 'form', event: @event, event_history: @event_history

.panel
  = link_to '戻る', [@event, @event_history], class: 'button'

- set_meta_title_for(@event.name, "#{EventHistory.human_attribute_name(:resolution)}を編集する")