Vche-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    resource :heartbeat, only: :show
  end

  resource :home, controller: :home, only: :show

  namespace :my do
    resources :offline_schedules

    resources :events, only: [:index]
    resources :event_follow_requests, only: :index do
      member do
        post :accept
        post :decline
      end
    end

    resource :user do
      get :delete_form
      post :delete
    end

    resource :settings, only: [:show]
    resource :password, only: [:edit, :update]
  end

  resources :users, except: [:destroy] do
    member do
      get :info
      get :events
    end
    resources :accounts, controller: 'users/accounts' do
      member do
        get :info
      end
    end
    resources :event_memories, controller: 'users/event_memories'
  end

  resources :events do
    get :select, on: :new
    member do
      get :info
      post :follow
      post :unfollow
      post :add_user
      post :change_user
      post :remove_user
      get :appeal
    end
    resources :event_schedules
    resources :event_histories, controller: 'events/event_histories' do
      resources :event_attendances, controller: 'events/event_histories/event_attendances', only: :index
      member do
        get :info
        post :attend
        post :unattend
        post :add_user
        post :change_user
        post :remove_user
        get :appeal
      end
      resource :resolution, controller: 'events/event_histories/resolutions', only: [:edit, :update]
      resource :reschedule, controller: 'events/event_histories/reschedules', only: [:new, :create]
    end
    resources :event_follows, controller: 'events/event_follows', only: :index
    resources :event_follow_requests, controller: 'events/event_follow_requests', only: :index do
      member do
        post :withdraw
      end
    end
    resources :event_appeals, controller: 'events/event_appeals', only: [:edit, :update]

    resource :owner, controller: 'events/owners', only: [:edit, :update] do
      get :introduction
    end
    resource :visibility, controller: 'events/visibilities', only: [:show, :edit, :update]
    resource :settings, controller: 'events/settings', only: [:show]
  end

  resources :hashtags, only: [:index, :show]

  get 'login' => 'sessions#new', :as => :login
  post 'login' => "sessions#create"
  post 'logout' => 'sessions#destroy', :as => :logout
  post '/sessions/purge' => 'sessions#purge', :as => :purge_sessions

  get 'oauth/:provider/oauth', to: 'oauths#oauth', :as => :auth_at_provider
  get 'oauth/:provider/callback', to: 'oauths#callback'

  get 'tos' => 'agreements#tos', :as => :tos
  get 'privacy_policy' => 'agreements#privacy_policy', :as => :privacy_policy

  resources :agreements, only: [] do
    collection do
      get :confirm
      post :agree
    end
  end

  resource :recovery, only: [:new, :create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :done
    end
  end

  root :to => 'calendar#index'

  direct :support_email do
    Rails.application.config.x.vche.support_email
  end

  direct :support_github do
    Rails.application.config.x.vche.support_github
  end

  direct :support_twitter do
    Rails.application.config.x.vche.support_twitter
  end

  direct :support_discord do
    Rails.application.config.x.vche.support_discord
  end

  ActiveAdmin.routes(self)
end

Vche-rails/app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :bigint           not null, primary key
#  uid          :string(255)
#  display_name :string(255)
#  platform_id  :bigint           not null
#  url          :string(255)
#  user_id      :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_accounts_on_platform_id  (platform_id)
#  index_accounts_on_uid          (uid) UNIQUE
#  index_accounts_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (platform_id => platforms.id)
#  fk_rails_...  (user_id => users.id)
#
class Account < ApplicationRecord
  include Vche::Uid
  include Vche::UidQuery

  belongs_to :user
  belongs_to :platform
end

Vche-rails/app/controllers/users/accounts_controller.rb
class Users::AccountsController < ApplicationController::Bootstrap
  before_action :find_parent_user

  def index
    authorize!
    @accounts = @user.accounts
  end

  def show
    authorize!
    @account = find_account
  end

  def info
    authorize!
    @account = find_account
  end

  def new
    @account = @user.accounts.build
    authorize! @account
  end

  def edit
    @account = find_account
    authorize! @account
  end

  def create
    @account = @user.accounts.new(account_params)
    authorize! @account

    if @account.save
      redirect_to user_accounts_path(@user), notice: I18n.t('notice.users/accounts.create.success')
    else
      render :new
    end
  end

  def update
    @account = find_account
    authorize! @account
    if @account.update(account_params)
      redirect_to [@user, @account], notice: I18n.t('notice.users/accounts.update.success')
    else
      render :edit
    end
  end

  def destroy
    @account = find_account
    authorize! @account
    @account.destroy
    redirect_to user_accounts_url(@user), notice: I18n.t('notice.users/accounts.destroy.success')
  end

  private

  def find_parent_user
    @user = User.friendly.secret_or_over.find(params[:user_id])
  end

  def find_account
    @user.accounts.find_by(uid: params[:id])
  end

  def account_params
    params.require(:account).permit(:display_name, :platform_id, :url)
  end
end

Vche-rails/app/helpers/account_helper.rb
module AccountHelper
  def account_icon_tag(account, size: :medium)
    # class_name = size ? "account__icon -#{size}" : 'account__icon'
    # size_num = icon_size_num(size)

    # image_tag('/account_128x128.png', class: class_name, width: size_num, height: size_num, alt: account.display_name, title: account.display_name)

    tag.span
  end
end

Vche-rails/app/views/accounts/_cards.html.slim
- accounts ||= nil
- card_cloud ||= false
- _layout = card_cloud ? 'card_cloud' : 'card_list'

div class="accounts -#{_layout}"
  - accounts.each do |account|
    .account.-card
      = link_to account_icon_tag(account), [account.user, account]
      span.display_name = link_to account.display_name, [account.user, account]
      = inline_platform_tag account.platform

Vche-rails/app/views/accounts/_pretty.html.slim
- account ||= nil

.account.-pretty
  .field
    label = Account.human_attribute_name(:platform)
    .value = account.platform.name
  - if account.url.present?
    .field
      label
      .relation
        = external_link_to account.url, account.url, class: 'button -external'

  .actions
    - if loyalty(account, 'users/accounts').info?
      = link_to '情報を見る', info_user_account_path(user, account), class: :button
    - if loyalty(account, 'users/accounts').edit?
      = link_to '編集する', edit_user_account_path(user, account), class: :button
    - if loyalty(account, 'users/accounts').destroy?
      = link_to '削除する', user_account_path(user, account), method: :delete, class: 'button -negative'

Vche-rails/app/views/accounts/_table.html.slim
- account ||= nil

.account.-table
  .field
    label = Account.human_attribute_name(:display_name)
    .value = account.display_name
  .field
    label = Account.human_attribute_name(:platform)
    .value = account.platform.name
  .field
    label = Account.human_attribute_name(:url)
    .value = account.url

  .actions
    - if loyalty(account, 'users/accounts').edit?
      = link_to '編集する', edit_user_account_path(user, account), class: 'button'
    - if loyalty(account, 'users/accounts').destroy?
      = link_to '削除する', user_account_path(user, account), method: :delete, class: 'button -negative'