Vche-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    resource :heartbeat, only: :show
  end

  resource :home, controller: :home, only: :show

  namespace :my do
    resources :offline_schedules

    resources :events, only: [:index]
    resources :event_follow_requests, only: :index do
      member do
        post :accept
        post :decline
      end
    end

    resource :user do
      get :delete_form
      post :delete
    end

    resource :settings, only: [:show]
    resource :password, only: [:edit, :update]
  end

  resources :users, except: [:destroy] do
    member do
      get :info
      get :events
    end
    resources :accounts, controller: 'users/accounts' do
      member do
        get :info
      end
    end
    resources :event_memories, controller: 'users/event_memories'
  end

  resources :events do
    get :select, on: :new
    member do
      get :info
      post :follow
      post :unfollow
      post :add_user
      post :change_user
      post :remove_user
      get :appeal
    end
    resources :event_schedules
    resources :event_histories, controller: 'events/event_histories' do
      resources :event_attendances, controller: 'events/event_histories/event_attendances', only: :index
      member do
        get :info
        post :attend
        post :unattend
        post :add_user
        post :change_user
        post :remove_user
        get :appeal
      end
      resource :resolution, controller: 'events/event_histories/resolutions', only: [:edit, :update]
      resource :reschedule, controller: 'events/event_histories/reschedules', only: [:new, :create]
    end
    resources :event_follows, controller: 'events/event_follows', only: :index
    resources :event_follow_requests, controller: 'events/event_follow_requests', only: :index do
      member do
        post :withdraw
      end
    end
    resources :event_appeals, controller: 'events/event_appeals', only: [:edit, :update]

    resource :owner, controller: 'events/owners', only: [:edit, :update] do
      get :introduction
    end
    resource :visibility, controller: 'events/visibilities', only: [:show, :edit, :update]
    resource :settings, controller: 'events/settings', only: [:show]
  end

  resources :hashtags, only: [:index, :show]

  get 'login' => 'sessions#new', :as => :login
  post 'login' => "sessions#create"
  post 'logout' => 'sessions#destroy', :as => :logout
  post '/sessions/purge' => 'sessions#purge', :as => :purge_sessions

  get 'oauth/:provider/oauth', to: 'oauths#oauth', :as => :auth_at_provider
  get 'oauth/:provider/callback', to: 'oauths#callback'

  get 'tos' => 'agreements#tos', :as => :tos
  get 'privacy_policy' => 'agreements#privacy_policy', :as => :privacy_policy

  resources :agreements, only: [] do
    collection do
      get :confirm
      post :agree
    end
  end

  resource :recovery, only: [:new, :create]

  resources :feedbacks, only: [:new, :create] do
    collection do
      get :done
    end
  end

  root :to => 'calendar#index'

  direct :support_email do
    Rails.application.config.x.vche.support_email
  end

  direct :support_github do
    Rails.application.config.x.vche.support_github
  end

  direct :support_twitter do
    Rails.application.config.x.vche.support_twitter
  end

  direct :support_discord do
    Rails.application.config.x.vche.support_discord
  end

  ActiveAdmin.routes(self)
end

Vche-rails/app/models/operations/event_history/request_update_user_role.rb
class Operations::EventHistory::RequestUpdateUserRole
  include Operations::Operation

  class Outsider < StandardError; end

  def initialize(event_history:, creator:, user:, approver:, role:)
    @event_history = event_history
    @creator = creator
    @user = user
    @approver = approver
    @role = role&.to_sym
  end

  def validate
    raise ArgumentError if role == :irrelevant
    raise Outsider unless EventAttendance.backstage_role?(role) || EventAttendance.backstage_role?(current_role)
  end

  def perform
    if role
      event_follow_requests.find_or_initialize_by({}).tap do |efr|
        efr.assign_attributes(approver: approver, role: role, message: '', created_user: creator, updated_user: creator)
        efr.save!
      end
    else
      event_follow_requests.destroy_all
    end
  end

  private

  attr_reader :event_history, :creator, :user, :approver, :role

  def event_follow_requests
    user.event_follow_requests.where(event: event_history.event, started_at: event_history.started_at)
  end

  def current_role
    user.event_attendances.for_event_history(event_history).first&.role&.to_sym || :irrelevant
  end
end

Vche-rails/app/controllers/event_histories_controller.rb
class EventHistoriesController < ApplicationController
  before_action :find_parent_event
  skip_before_action :require_login, only: [:index, :show]

  def index
    @event_histories = @event.event_histories.order(started_at: :desc).page(params[:page])
    @user = current_user
  end

  def show
    @event_history = find_event_history
    @user = current_user
  end

  def at
    started_at = Time.zone.parse(params[:datetime])
    @event_history = @event.recent_schedule([started_at.beginning_of_day]).detect { |h| h.started_at = started_at }
    render :show
  end

  def new
    @event_history = EventHistory.new
  end

  def edit
    @event_history = find_event_history
  end

  def create
    @event_history = @event.event_histories.build(event_history_params)
    authorize! @event_history
    @event_history.created_user = current_user
    @event_history.updated_user = current_user

    if @event_history.save
      redirect_to event_event_history_path(@event, @event_history), notice: 'EventHistory was successfully created'
    else
      render :new
    end
  end

  def update
    @event_history = find_event_history
    authorize! @event_history
    @event_history.updated_user = current_user
    if @event_history.update(event_history_params)
      redirect_to event_event_history_path(@event, @event_history), notice: 'EventHistory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event_history = find_event_history
    authorize! @event_history
    @event_history.destroy
    redirect_to events_url, notice: 'EventHistory was successfully destroyed.'
  end

  def attend
    @event_history = find_event_history
    authorize! @event_history

    role = current_user.following_event_as_backstage_member?(@event) || :participant
    if current_user.event_attendances.for_event_history(@event_history).create!(role: role)
      redirect_to event_event_history_path(@event, @event_history), notice: 'Attended.'
    else
      redirect_to event_event_history_path(@event, @event_history)
    end
  end

  def unattend
    @event_history = find_event_history
    authorize! @event_history

    if current_user.event_attendances.audience.for_event_history(@event_history).delete_all
      redirect_to event_event_history_path(@event, @event_history), notice: 'Unattended.'
    else
      redirect_to event_event_history_path(@event, @event_history)
    end
  end

  def add_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    if @user.event_attendances.for_event_history(@event_history).create!(role: params[:role])
      redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: 'Added User.'
    else
      redirect_to event_event_history_event_attendances_path(@event, @event_history)
    end
  end

  def remove_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    if @user.event_attendances.for_event_history(@event_history).delete_all
      redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: 'Removed User.'
    else
      redirect_to event_event_history_event_attendances_path(@event, @event_history)
    end
  end

  private

  def find_user
    User.friendly.find(params[:user_id])
  end

  def find_parent_event
    @event = Event.friendly.find(params[:event_id])
  end

  def find_event_history
    @event.find_or_build_history(Time.zone.parse(params[:id]))
  end

  def event_history_params
    p = params.require(:event_history).permit(:visibility, :assembled_at, :opened_at, :started_at, :ended_at, :closed_at, :resolution)
  end
end

Vche-rails/app/controllers/events/event_histories/event_attendances_controller.rb
class Events::EventHistories::EventAttendancesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def index
    authorize! @event_history
    @user = current_user
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end
end

Vche-rails/app/controllers/events/event_histories/reschedules_controller.rb
class Events::EventHistories::ReschedulesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def new
    authorize! @event_history
    @user = current_user
  end

  def create
    authorize! @event_history
    @new_event_history = Operations::EventHistory::Reschedule.new(event_history: @event_history, params: reschedule_params, user: current_user).perform!
    redirect_to [@event, @new_event_history], notice: I18n.t('notice.events/event_histories/reschedules.create.success')
  rescue Operations::EventHistory::Reschedule::Unchanged
    redirect_to [@event, @event_history], notice: I18n.t('notice.events/event_histories/reschedules.create.unchanged')
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end

  def reschedule_params
    params.require(:event_history).permit(
      :capacity,
      :assembled_at, :opened_at, :started_at, :ended_at, :closed_at
    )
  end
end

Vche-rails/app/controllers/events/event_histories/resolutions_controller.rb
class Events::EventHistories::ResolutionsController < ApplicationController::Bootstrap
  before_action :find_parent_event
  before_action :find_parent_event_history

  def edit
    authorize! @event_history
  end

  def update
    authorize! @event_history
    if @event_history.update(update_params)
      redirect_to [@event, @event_history], notice: I18n.t('notice.events/event_histories/resolutions.update.success')
    else
      render :edit
    end
  end

  private

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_parent_event_history
    @event_history = @event.find_or_build_history(Time.zone.parse(params[:event_history_id]))
  end

  def update_params
    params.require(:event_history).permit(:resolution)
  end
end

Vche-rails/app/controllers/events/event_histories_controller.rb
class Events::EventHistoriesController < ApplicationController::Bootstrap
  before_action :find_parent_event
  skip_before_action :require_login, only: [:index, :show, :appeal]

  def index
    @event_histories = @event.event_histories.order(started_at: :desc).page(params[:page])
    @user = current_user
    authorize! @event
  end

  def show
    @event_history = find_event_history
    authorize! @event_history
    @user = current_user
  end

  def info
    @event_history = find_event_history
    authorize! @event_history
    @user = current_user
  end

  def at
    started_at = Time.zone.parse(params[:datetime])
    @event_history = @event.recent_histories([started_at.beginning_of_day]).detect { |h| h.started_at = started_at }
    authorize! @event_history
    render :show
  end

  def new
    authorize! @event
    @event_history = @event.event_histories.build
  end

  def edit
    @event_history = find_event_history
    authorize! @event_history
  end

  def create
    @event_history = @event.event_histories.build(create_params)
    authorize! @event_history
    @event_history.created_user = current_user
    @event_history.updated_user = current_user

    if @event_history.save
      redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.create.success')
    else
      render :new
    end
  end

  def update
    @event_history = find_event_history
    authorize! @event_history
    @event_history.updated_user = current_user
    if @event_history.update(update_params)
      redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.update.success')
    else
      render :edit
    end
  end

  def destroy
    @event_history = find_event_history
    authorize! @event_history
    @event_history.destroy
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.destroy.success')
  end

  def attend
    @event_history = find_event_history
    authorize! @event_history

    role = current_user.following_event?(@event) || @event_history.default_audience_role
    Operations::EventHistory::UpdateUserAttendance.new(event_history: @event_history, user: current_user, role: role).perform!
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.attend.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserAttendance::UserIsAudience
    redirect_to event_event_history_path(@event, @event_history)
  end

  def unattend
    @event_history = find_event_history
    authorize! @event_history

    Operations::EventHistory::UpdateUserAttendance.new(event_history: @event_history, user: current_user, role: nil).perform!
    redirect_to event_event_history_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.unattend.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserAttendance::UserIsAudience
    redirect_to event_event_history_path(@event, @event_history)
  end

  def add_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::RequestUpdateUserRole.new(
      event_history: @event_history, creator: current_user, user: @user, approver: @user, role: params[:role]
    ).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.add_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::RequestUpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.add_user.outsider')
  end

  def change_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::UpdateUserRole.new(event_history: @event_history, user: @user, role: params[:role]).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.change_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.change_user.outsider')
  end

  def remove_user
    @event_history = find_event_history
    authorize! @event_history
    @user = find_user

    Operations::EventHistory::UpdateUserRole.new(event_history: @event_history, user: @user, role: nil).perform!
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.remove_user.success')
  rescue ActiveRecord::RecordInvalid
    redirect_to event_event_history_event_attendances_path(@event, @event_history)
  rescue Operations::EventHistory::UpdateUserRole::Outsider
    redirect_to event_event_history_event_attendances_path(@event, @event_history), notice: I18n.t('notice.events/event_histories.remove_user.outsider')
  end

  def appeal
    @event_history = find_event_history
    authorize! @event_history
    redirect_to helpers.intent_url_for(@event_history)
  end

  private

  def find_user
    User.friendly.secret_or_over.find(params[:user_id])
  end

  def find_parent_event
    @event = Event.friendly.secret_or_over.find(params[:event_id])
  end

  def find_event_history
    @event.find_or_build_history(Time.zone.parse(params[:id]))
  end

  def create_params
    params.require(:event_history).permit(
      :resolution, :capacity, :default_audience_role,
      :assembled_at, :opened_at, :started_at, :ended_at, :closed_at
    )
  end

  def update_params
    params.require(:event_history).permit(
      :resolution, :capacity, :default_audience_role,
      :assembled_at, :opened_at, :ended_at, :closed_at
    )
  end
end

Vche-rails/app/helpers/event_history_helper.rb
module EventHistoryHelper
  def capacity_and_attendance_text(event_history)
    if event_history.capacity > 0
      "#{event_history.event_audiences.count} / #{event_history.capacity} (#{event_history.event_backstage_members.count})"
    else
      "#{event_history.event_audiences.count} (#{event_history.event_backstage_members.count})"
    end
  end
end

Vche-rails/app/views/event_histories/_cards.html.slim
- event ||= nil
- event_histories ||= nil
- edit ||= false
- limit ||= nil
- card_cloud ||= false
- _layout = card_cloud ? 'card_cloud' : 'card_list'
- _count = limit && event_histories.count
- event_histories = event_histories.limit(limit) if limit

div class="event_histories -#{_layout}"
  - event_histories.each do |event_history|
    - _event = event || event_history.event
    .event_history.-card
      span.resolution = event_history.resolution_emoji_text
      - unless event
        span.name = link_to _event.name, _event
      = link_to event_event_history_path(_event, event_history), class: :time_span do
        - started_at, ended_at = time_span_text(event_history.started_at, event_history.ended_at)
        span.started_at = started_at
        span.sep -
        span.ended_at = ended_at
      - if edit && loyalty(event_history, 'events/event_histories').edit?
        = link_to '編集する', edit_event_event_history_path(_event, event_history), class: 'button'
  - if _count && _count > limit
    = "ほか #{_count - limit} 件"

Vche-rails/app/views/event_histories/_cell_event_cards.html.slim
- cell_events ||= nil
- card_cloud ||= false
- edit ||= false
- _layout = card_cloud ? 'card_cloud' : 'card_list'

div class="event_histories -#{_layout}"
  - cell_events.each do |cell_event|
    - event_history = cell_event.event_history
    - event = event_history.event
    - role_text = cell_event.role_text
    .event_history.-card
      span.resolution = event_history.resolution_emoji_text
      span.name = link_to event.name, event
      = link_to event_event_history_path(event, event_history), class: :time_span do
        - started_at, ended_at = time_span_text(event_history.started_at, event_history.ended_at)
        span.started_at = started_at
        span.sep -
        span.ended_at = ended_at
      - if role_text
        span.role = role_text
      - if edit
        = external_link_to 'ツイート', appeal_event_path(event), class: 'button -external -tweet'

Vche-rails/app/views/event_histories/_pretty.html.slim
- event ||= nil
- event_history ||= nil

.event_history.-pretty
  .field
    label = EventHistory.human_attribute_name(:backstage_members)
    .relation
      = render 'event_attendances/cards', event_history: event_history, event_attendances: event_history.event_backstage_members, card_cloud: true
      span.actions
        - if loyalty(event_history, 'events/event_histories').add_user?
          = link_to 'スタッフを割り当てる', event_event_history_event_attendances_path(event, event_history), class: :button
        = render 'events/event_follow_requests/link', event: @event
  - if event_history.assembled_at && loyalty(event_history, 'events/event_histories').backstage?
    .field
      label = EventHistory.human_attribute_name(:assembled_at)
      .value = l(event_history.assembled_at)
  - if event_history.opened_at
    .field
      label = EventHistory.human_attribute_name(:opened_at)
      .value = l(event_history.opened_at) if event_history.opened_at
  - if event_history.started_at
    .field
      label = EventHistory.human_attribute_name(:started_at)
      .value = l(event_history.started_at)
  -  if event_history.ended_at
    .field
      label = EventHistory.human_attribute_name(:ended_at)
      .value = l(event_history.ended_at)
  - if event_history.closed_at && loyalty(event_history, 'events/event_histories').backstage?
    .field
      label = EventHistory.human_attribute_name(:closed_at)
      .value = l(event_history.closed_at)

  .field
    label = EventHistory.human_attribute_name(:capacity)
    .value = event_history.capacity

  .actions
    - if loyalty(event_history, 'events/event_histories').info?
      = link_to '情報を見る', info_event_event_history_path(event, event_history), class: :button
    - if loyalty(event_history, 'events/event_histories').edit?
      = link_to '編集する', edit_event_event_history_path(event, event_history), class: 'button'
    - if loyalty(event_history, 'events/event_histories').destroy?
      - if event_history.scheduled?
        = link_to 'リセットする', event_event_history_path(event, event_history), method: :delete, class: 'button -negative', data: {confirm: "開催回の情報を消去しますか？\n（参加表明や思い出は消去されません。）"}
      - else
        = link_to '削除する', event_event_history_path(event, event_history), method: :delete, class: 'button -negative', data: {confirm: "開催回の情報を消去しますか？\n（参加表明や思い出は消去されません。）"}

  = render 'editor_info', resource: event_history

Vche-rails/app/views/event_histories/_strip.html.slim
- event_history ||= nil
- event ||= nil
- user ||= nil

.event_history.-strip
  div
    span.started_at
      = "#{EventHistory.model_name.human}:"
      = link_to(l(event_history.started_at), event_event_history_path(event, event_history), class: :strip__title)
    '
    = link_to event_event_history_event_attendances_path(event, event_history), class: 'link attendances' do
      span.label 参加者
      '
      = capacity_and_attendance_text(event_history)
    - if user
      '
      span.attending_event = user.attending_event?(event_history)&.text || EventAttendance.role.irrelevant.text
    span.actions
      - if loyalty(event_history, 'events/event_histories').attend?
        = link_to '参加表明する', attend_event_event_history_path(event, event_history), method: :post, class: 'button'
      - if loyalty(event_history, 'events/event_histories').unattend?
        = link_to '参加表明を解除', unattend_event_event_history_path(event, event_history), method: :post, class: 'button'
      - if loyalty(event_history, 'events/event_histories').memory?
        = link_to '思い出を書く', new_user_event_memory_path(user, event_id: event, started_at: event_history), class: 'button'
      - if loyalty(event_history, 'events/event_histories').appeal?
        = external_link_to 'ツイート', appeal_event_event_history_path(event, event_history), class: 'button -external -tweet'

  div
    span.resolution = event_history.resolution_emoji_text
    - if user
      '
      span.actions
        - if loyalty(event_history, 'events/event_histories/resolutions').update?
          = render 'events/event_histories/resolutions/quick_inline_forms', event: event, event_history: event_history
        - if loyalty(event_history, 'events/event_histories/resolutions').edit?
          = link_to '状態を変更する', edit_event_event_history_resolution_path(event, event_history), class: 'button'
        - if loyalty(event_history, 'events/event_histories/reschedules').new?
          = link_to '日程を変更する', new_event_event_history_reschedule_path(event, event_history), class: 'button'

Vche-rails/app/views/event_histories/_table.html.slim
- event ||= nil
- event_history ||= nil

.event_history.-table
  .field
    label = EventHistory.human_attribute_name(:resolution)
    .value = event_history.resolution_emoji_text
  .field
    label = EventHistory.human_attribute_name(:backstage_members)
    .relation
      = render 'event_attendances/cards', event_history: event_history, event_attendances: event_history.event_backstage_members, card_cloud: true
      span.actions
        - if loyalty(event_history, 'events/event_histories').add_user?
          = link_to 'スタッフを割り当てる', event_event_history_event_attendances_path(event, event_history), class: :button
        = render 'events/event_follow_requests/link', event: @event
  - if loyalty(event_history, 'events/event_histories').backstage?
    .field
      label = EventHistory.human_attribute_name(:assembled_at)
      .value = l(event_history.assembled_at) if event_history.assembled_at
  .field
    label = EventHistory.human_attribute_name(:opened_at)
    .value = l(event_history.opened_at) if event_history.opened_at
  .field
    label = EventHistory.human_attribute_name(:started_at)
    .value = l(event_history.started_at)
  .field
    label = EventHistory.human_attribute_name(:ended_at)
    .value = l(event_history.ended_at) if event_history.ended_at
  - if loyalty(event_history, 'events/event_histories').backstage?
    .field
      label = EventHistory.human_attribute_name(:closed_at)
      .value = l(event_history.closed_at) if event_history.closed_at

  .field
    label = EventHistory.human_attribute_name(:capacity)
    .value = event_history.capacity
  .field
    label = EventHistory.human_attribute_name(:default_audience_role)
    .value = EventAttendance.role.find_value(event_history.default_audience_role).text

  .actions
    - if loyalty(event_history, 'events/event_histories').edit?
      = link_to '編集する', edit_event_event_history_path(event, event_history), class: 'button'
    - if loyalty(event_history, 'events/event_histories').destroy?
      - if event_history.scheduled?
        = link_to 'リセットする', event_event_history_path(event, event_history), method: :delete, class: 'button -negative', data: {confirm: "開催回の情報を消去しますか？\n（参加表明や思い出は消去されません。）"}
      - else
        = link_to '削除する', event_event_history_path(event, event_history), method: :delete, class: 'button -negative', data: {confirm: "開催回の情報を消去しますか？\n（参加表明や思い出は消去されません。）"}

  = render 'editor_info', resource: event_history

Vche-rails/app/views/event_histories/index.html.slim
h1 = EventHistory.model_name.human

= render 'events/strip', event: @event, user: @user

= render 'cards', event: @event, event_histories: @event_histories, edit: false
= paginate @event_histories

= link_to 'New', new_event_event_history_path(@event), class: 'button'

Vche-rails/app/views/event_histories/show.html.slim
h1 = "#{EventHistory.model_name.human}詳細"

= render 'events/strip', event: @event, user: @user

= render 'event_histories/strip', event: @event, event_history: @event_history, user: @user

= render 'table', event: @event, event_history: @event_history

h2 = "#{Event.model_name.human}情報"

= render 'events/table', event: @event